name: Publish Docker Images

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker images to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for healthyglam-api_gateway
        id: meta_api_gateway
        uses: docker/metadata-action@v2
        with:
          images: irhadudheen/healthyglam-api_gateway

      - name: Build and push healthyglam-api_gateway Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Backend/API-gateway
          dockerfile: Dockerfile
          push: true
          tags: ${{ steps.meta_api_gateway.outputs.tags }}
          labels: ${{ steps.meta_api_gateway.outputs.labels }}

      - name: Extract metadata for healthyglam-comment_service
        id: meta_comment_service
        uses: docker/metadata-action@v2
        with:
          images: irhadudheen/healthyglam-comment_service

      - name: Build and push healthyglam-comment_service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Backend/comment-service
          dockerfile: Dockerfile
          push: true
          tags: ${{ steps.meta_comment_service.outputs.tags }}
          labels: ${{ steps.meta_comment_service.outputs.labels }}

      - name: Extract metadata for healthyglam-auth_service
        id: meta_auth_service
        uses: docker/metadata-action@v2
        with:
          images: irhadudheen/healthyglam-auth_service

      - name: Build and push healthyglam-auth_service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Backend/auth-service
          dockerfile: Dockerfile
          push: true
          tags: ${{ steps.meta_auth_service.outputs.tags }}
          labels: ${{ steps.meta_auth_service.outputs.labels }}

      - name: Extract metadata for healthyglam-post_details_service
        id: meta_post_details_service
        uses: docker/metadata-action@v2
        with:
          images: irhadudheen/healthyglam-post_details_service

      - name: Build and push healthyglam-post_details_service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Backend/postDetails-service
          dockerfile: Dockerfile
          push: true
          tags: ${{ steps.meta_post_details_service.outputs.tags }}
          labels: ${{ steps.meta_post_details_service.outputs.labels }}

      - name: Extract metadata for healthyglam-post_service
        id: meta_post_service
        uses: docker/metadata-action@v2
        with:
          images: irhadudheen/healthyglam-post_service

      - name: Build and push healthyglam-post_service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Backend/post-service
          dockerfile: Dockerfile
          push: true
          tags: ${{ steps.meta_post_service.outputs.tags }}
          labels: ${{ steps.meta_post_service.outputs.labels }}
